# Generated by Django 4.0.4 on 2022-06-28 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cli', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_cli', models.CharField(max_length=150)),
                ('ap_cli', models.CharField(max_length=150)),
                ('run_cli', models.CharField(max_length=9)),
                ('fono', models.CharField(max_length=13)),
                ('direccion', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('foto', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'db_table': 'db_cliente',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('cod_comuna', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_comuna', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'db_comuna',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('estado_compra', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'db_estado_comp',
            },
        ),
        migrations.CreateModel(
            name='listaDeseado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('cod', models.IntegerField()),
                ('prec', models.IntegerField()),
                ('sto', models.IntegerField()),
                ('imag', models.ImageField(null=True, upload_to='listaDeseos')),
            ],
            options={
                'db_table': 'db_listaDeseos',
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo_prod', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_prod', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'db_tipoProducto',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_us', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'db_tipoUsuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_usuario', models.CharField(max_length=50)),
                ('ap_usuario', models.CharField(max_length=150)),
                ('run_usuario', models.IntegerField()),
                ('dv_usuario', models.CharField(max_length=1)),
                ('fono', models.CharField(max_length=13)),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipousuario')),
            ],
            options={
                'db_table': 'db_usuarios',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suscripcion', models.BooleanField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
            options={
                'db_table': 'db_sus',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('img', models.ImageField(null=True, upload_to='productos')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoproducto')),
            ],
            options={
                'db_table': 'db_producto',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('cod_compra', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom_prod', models.CharField(max_length=50)),
                ('cod_prod', models.IntegerField()),
                ('img', models.ImageField(null=True, upload_to='carro')),
                ('cant', models.IntegerField()),
                ('total', models.IntegerField()),
                ('estado_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
            ],
            options={
                'db_table': 'db_compra',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='comuna',
            field=models.ForeignKey(choices=[[0, 'Puente Alto'], [1, 'La Florida'], [2, 'La Pintana'], [3, 'San Bernardo']], on_delete=django.db.models.deletion.CASCADE, to='app.comuna'),
        ),
    ]
