# Generated by Django 4.0.4 on 2022-06-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripcion',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='id',
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='user',
            field=models.CharField(default=1, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
